name: E2E Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.3"
          - "8.4"
        stability:
          - lowest
          - stable
        package:
          - l5-swagger
          - laravel-openapi
        include:
          - option: --ignore-platform-req=php
            php: "8.4"

    name: PHP:${{ matrix.php }} / ${{ matrix.package }} / ${{ matrix.stability }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer update --prefer-${{ matrix.stability }} ${{ matrix.option }} --no-interaction --no-progress --ansi
        working-directory: e2e/${{ matrix.package }}

      - name: Run Unit tests
        run: vendor/bin/phpunit
        working-directory: e2e/${{ matrix.package }}

      - name: Test create cache
        run: ./artisan openapi-validator:cache --ansi
        working-directory: e2e/${{ matrix.package }}

      - name: Test clear cache
        run: ./artisan openapi-validator:clear --ansi
        working-directory: e2e/${{ matrix.package }}

      - name: Publish config file
        run: ./artisan openapi-validator:publish --ansi
        working-directory: e2e/${{ matrix.package }}

      - name: Force publish config file
        run: ./artisan openapi-validator:publish --force --ansi
        working-directory: e2e/${{ matrix.package }}
