name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        laravel:
          - "^10.0"
          - "^11.0"
          - "^12.0"
          - "^13.0"
        stability:
          - lowest
          - stable
        include:
          - current: 1
            php: "8.4"
            laravel: "^12.0"
            stability: stable
        exclude:
          - laravel: "^11.0"
            php: "8.1"
          - laravel: "^12.0"
            php: "8.1"
          - laravel: "^13.0"
            php: "8.1"
          - laravel: "^13.0"
            php: "8.2"
          - laravel: "^10.0"
            stability: lowest
          - laravel: "^11.0"
            stability: lowest

    name: PHP:${{ matrix.php }} / Laravel:${{ matrix.laravel }} / ${{ matrix.stability }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP, with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        run: composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update --ansi

      - name: Allow installing end-of-life Laravel versions
        if: ${{ matrix.laravel == '^10.0' || matrix.laravel == '^11.0' }}
        run: composer config policy.advisories.ignore laravel/framework

      # Remove once tartanlegrand/laravel-openapi releases a version that supports Laravel 13
      # https://github.com/Nova-Edge/laravel-openapi/pull/52
      - name: Allow installing Laravel OpenAPI with Laravel 13
        if: ${{ matrix.laravel == '^13.0' }}
        run: |
          composer config repositories.laravel-openapi '{
            "type": "package",
            "package": {
              "name": "tartanlegrand/laravel-openapi",
              "version": "2.1.2.1",
              "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/Nova-Edge/laravel-openapi/zipball/v2.1.2"
              },
              "require": {
                "php": "^8.0",
                "ext-json": "*",
                "goldspecdigital/oooas": "^2.7.1",
                "laravel/framework": "^11.0|^12.0|^13.0",
                "phpdocumentor/reflection-docblock": "^5.0"
              },
              "autoload": {
                "psr-4": {
                  "Vyuldashev\\LaravelOpenApi\\": "src/"
                }
              },
              "extra": {
                "laravel": {
                  "providers": [
                    "Vyuldashev\\LaravelOpenApi\\OpenApiServiceProvider"
                  ]
                }
              }
            }
          }'

      - name: Uninstall packages that is not necessary for the current matrix
        if: ${{ !matrix.current }}
        run: composer remove --dev friendsofphp/php-cs-fixer larastan/larastan phpstan/phpstan phpstan/phpstan-mockery --no-interaction --no-update

      - name: Install Composer dependencies
        run: composer update --prefer-${{ matrix.stability }} --no-interaction --no-progress --ansi

      - name: Run Code Format Check
        if: ${{ matrix.current }}
        run: vendor/bin/php-cs-fixer check --show-progress=none --ansi

      - name: Run Static Analysis
        if: ${{ matrix.current }}
        run: vendor/bin/phpstan analyze --no-progress --ansi

      - name: Run Unit tests
        run: vendor/bin/phpunit --colors=always
